# Generated by Django 2.0.5 on 2018-05-28 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('required', models.BooleanField(default=False)),
                ('type', models.SmallIntegerField(choices=[(1, 'Text'), (2, 'Integer'), (3, 'Decimal'), (4, 'Date/Time'), (5, 'True/False'), (6, 'JSON')])),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'object',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('language', models.SmallIntegerField(choices=[(1, 'Sails.js')])),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, to='main_app.User'),
        ),
        migrations.AddField(
            model_name='object',
            name='project',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='main_app.Project'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='object',
            field=models.ForeignKey(db_column='object_id', on_delete=django.db.models.deletion.CASCADE, to='main_app.Object'),
        ),
        migrations.AlterUniqueTogether(
            name='object',
            unique_together={('name', 'project')},
        ),
    ]
