# Generated by Django 2.0.5 on 2018-05-28 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('name', 'object')},
        ),
        migrations.AlterModelTable(
            name='attribute',
            table='attribute',
        ),
    ]
