# Generated by Django 2.0.5 on 2019-04-27 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_auto_20190426_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attribute',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Object'),
        ),
        migrations.AlterField(
            model_name='object',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Project'),
        )
    ]
