# Generated by Django 2.2 on 2019-05-20 02:45

from django.db import migrations, models
import django.db.models.deletion
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190427_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_name', models.CharField(max_length=30)),
                ('kebab_case_name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('route', models.CharField(max_length=100)),
                ('method', models.SmallIntegerField(choices=[(main_app.models.HttpMethods(1), 'Create'), (main_app.models.HttpMethods(2), 'Read'), (main_app.models.HttpMethods(3), 'Update'), (main_app.models.HttpMethods(4), 'Delete')])),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Object')),
            ],
            options={
                'db_table': 'action',
                'unique_together': {('kebab_case_name', 'object')},
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Object'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Text'), (1, 'Integer'), (2, 'Decimal'), (3, 'Date/Time'), (4, 'True/False'), (5, 'List'), (6, 'Dictionary')]),
        ),
        migrations.CreateModel(
            name='ReturnValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=150)),
                ('key', models.CharField(max_length=30)),
                ('type', models.SmallIntegerField(choices=[(main_app.models.ReturnValueType(1), 'Static Text'), (main_app.models.ReturnValueType(2), 'Static Number'), (main_app.models.ReturnValueType(3), 'Result of Database Query'), (main_app.models.ReturnValueType(4), 'Object Attribute')])),
                ('static_string', models.CharField(blank=True, max_length=100)),
                ('static_number', models.FloatField(blank=True, null=True)),
                ('query_limit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('skip', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sort_direction', models.CharField(blank=True, choices=[('ASC', 'Ascending'), ('DESC', 'Descending')], max_length=4)),
                ('search_type', models.SmallIntegerField(blank=True, choices=[(main_app.models.SearchType(1), 'Equal To'), (main_app.models.SearchType(2), 'Greater Than'), (main_app.models.SearchType(3), 'Greater Than or Equal To'), (main_app.models.SearchType(4), 'Less Than'), (main_app.models.SearchType(5), 'Less Than or Equal To'), (main_app.models.SearchType(6), 'Not Equal')], null=True)),
                ('search_parameter', models.CharField(blank=True, max_length=100)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Action')),
                ('search_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main_app.Attribute')),
                ('sort_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main_app.Attribute')),
            ],
        ),
    ]
